using System.Xml.Linq;

namespace MusicalAlbums
{
    class Program
    {
        static void Main(string[] args)
        {
            XDocument xmlDoc = new XDocument();
            xmlDoc.Add(
                new XElement("music",
                    new XElement("artist", new XAttribute("name", "Radiohead"),
                        new XElement("album", new XAttribute("title", "The King of Limbs"),
                            new XElement("song", new XAttribute("title", "Bloom"), new XAttribute("length", "5:15")),
                            new XElement("song", new XAttribute("title", "Morning Mr Magpie"),
                                new XAttribute("length", "4:41")),
                            new XElement("song", new XAttribute("title", "Little by Little"),
                                new XAttribute("length", "4:27")),
                            new XElement("song", new XAttribute("title", "Feral"), new XAttribute("length", "3:13")),
                            new XElement("song", new XAttribute("title", "Lotus Flower"),
                                new XAttribute("length", "5:01")),
                            new XElement("song", new XAttribute("title", "Codex"), new XAttribute("length", "4:47")),
                            new XElement("song", new XAttribute("title", "Give Up the Ghost"),
                                new XAttribute("length", "4:50")),
                            new XElement("song", new XAttribute("title", "Separator"), new XAttribute("length", "5:20")),
                            new XElement("description",
                                "The King of Limbs is the eighth studio album by English rock band Radiohead, produced by Nigel Godrich. It was self-released on 18 February 2011 as a download in MP3 and WAV formats, followed by physical CD and 12\" vinyl releases on 28 March, a wider digital release via AWAL, and a special \"newspaper\" edition on 9 May 2011. The physical editions were released through the band\'s Ticker Tape imprint on XL in the United Kingdom, TBD in the United States, and Hostess Entertainment in Japan.",
                                new XAttribute("link", "http://en.wikipedia.org/wiki/The_King_of_Limbs"))),
                        new XElement("album", new XAttribute("title", "OK Computer"),
                            new XElement("song", new XAttribute("title", "Airbag"), new XAttribute("length", "4:44")),
                            new XElement("song", new XAttribute("title", "Paranoid Android"),
                                new XAttribute("length", "6:23")),
                            new XElement("song", new XAttribute("title", "Subterranean Homesick Alien"),
                                new XAttribute("length", "4:27")),
                            new XElement("song", new XAttribute("title", "Exit Music (For a Film)"),
                                new XAttribute("length", "4:24")),
                            new XElement("song", new XAttribute("title", "Let Down"), new XAttribute("length", "4:59")),
                            new XElement("song", new XAttribute("title", "Karma Police"),
                                new XAttribute("length", "4:21")),
                            new XElement("song", new XAttribute("title", "Fitter Happier"),
                                new XAttribute("length", "1:57")),
                            new XElement("song", new XAttribute("title", "Electioneering"),
                                new XAttribute("length", "3:50")),
                            new XElement("song", new XAttribute("title", "Climbing Up the Walls"),
                                new XAttribute("length", "4:45")),
                            new XElement("song", new XAttribute("title", "No Surprises"),
                                new XAttribute("length", "3:48")),
                            new XElement("song", new XAttribute("title", "Lucky"), new XAttribute("length", "4:19")),
                            new XElement("song", new XAttribute("title", "The Tourist"),
                                new XAttribute("length", "5:24")),
                            new XElement("description",
                                "OK Computer is the third studio album by the English alternative rock band Radiohead, released on 16 June 1997 on Parlophone in the United Kingdom and 1 July 1997 by Capitol Records in the United States. It marks a deliberate attempt by the band to move away from the introspective guitar-oriented sound of their previous album The Bends. Its layered sound and wide range of influences set it apart from many of the Britpop and alternative rock bands popular at the time and laid the groundwork for Radiohead\'s later, more experimental work.",
                                new XAttribute("link", "http://en.wikipedia.org/wiki/OK_Computer")))),
                    new XElement("artist", new XAttribute("name", "Portishead"),
                        new XElement("album", new XAttribute("title", "Dummy"),
                            new XElement("song", new XAttribute("title", "Mysterons"), new XAttribute("length", "5:02")),
                            new XElement("song", new XAttribute("title", "Sour Times"), new XAttribute("length", "4:11")),
                            new XElement("song", new XAttribute("title", "Strangers"), new XAttribute("length", "3:55")),
                            new XElement("song", new XAttribute("title", "It Could Be Sweet"),
                                new XAttribute("length", "4:16")),
                            new XElement("song", new XAttribute("title", "Wandering Star"),
                                new XAttribute("length", "4:51")),
                            new XElement("song", new XAttribute("title", "It's a Fire"),
                                new XAttribute("length", "3:49")),
                            new XElement("song", new XAttribute("title", "Numb"), new XAttribute("length", "3:54")),
                            new XElement("song", new XAttribute("title", "Roads"), new XAttribute("length", "5:02")),
                            new XElement("song", new XAttribute("title", "Pedestal"), new XAttribute("length", "3:39")),
                            new XElement("song", new XAttribute("title", "Biscuit"), new XAttribute("length", "5:01")),
                            new XElement("song", new XAttribute("title", "Glory Box"), new XAttribute("length", "5:06")),
                            new XElement("description",
                                "Dummy is the debut album of the Bristol-based group Portishead. Released in August 22, 1994 on Go! Discs, the album earned critical acclaim, winning the 1995 Mercury Music Prize. It is often credited with popularizing the trip-hop genre and is frequently cited in lists of the best albums of the 1990s. Although it achieved modest chart success overseas, it peaked at #2 on the UK Album Chart and saw two of its three singles reach #13. The album was certified gold in 1997 and has sold two million copies in Europe. As of September 2011, the album was certified double-platinum in the United Kingdom and has sold as of September 2011 825,000 copies.",
                                new XAttribute("link", "http://en.wikipedia.org/wiki/Dummy_%28album%29"))),
                        new XElement("album", new XAttribute("title", "Third"),
                            new XElement("song", new XAttribute("title", "Silence"), new XAttribute("length", "4:58")),
                            new XElement("song", new XAttribute("title", "Hunter"), new XAttribute("length", "3:57")),
                            new XElement("song", new XAttribute("title", "Nylon Smile"),
                                new XAttribute("length", "3:16")),
                            new XElement("song", new XAttribute("title", "The Rip"), new XAttribute("length", "4:29")),
                            new XElement("song", new XAttribute("title", "Plastic"), new XAttribute("length", "3:27")),
                            new XElement("song", new XAttribute("title", "We Carry On"),
                                new XAttribute("length", "6:27")),
                            new XElement("song", new XAttribute("title", "Deep Water"), new XAttribute("length", "1:31")),
                            new XElement("song", new XAttribute("title", "Machine Gun"),
                                new XAttribute("length", "4:43")),
                            new XElement("song", new XAttribute("title", "Small"), new XAttribute("length", "6:45")),
                            new XElement("song", new XAttribute("title", "Magic Doors"),
                                new XAttribute("length", "3:32")),
                            new XElement("song", new XAttribute("title", "Threads"), new XAttribute("length", "5:45")),
                            new XElement("description",
                                "Third is the third studio album by English musical group Portishead, released on 27 April 2008, on Island Records in the United Kingdom, two days after on Mercury Records in the United States, and on 30 April 2008 on Universal Music Japan in Japan. It is their first release in 10 years, and their first studio album in eleven years. Third entered the UK Album Chart at #2, and became the band\'s first-ever American Top 10 album on the Billboard 200, reaching #7 in its entry week.",
                                new XAttribute("link", "http://en.wikipedia.org/wiki/Third_%28Portishead_album%29"))))));

            xmlDoc.Save("../../Export/musical-library.xml");
        }
    }
}
